[package]
name = "oxide-enzyme"
version = "0.1.0"
authors = ["Lorenz Schmidt <bytesnake@mailbox.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enzyme-sys = { path = "enzyme-sys" }
llvm-sys = { version = "110", features = ["no-llvm-linking"] }
