# On every push this script is executed
on: push
name: Build and deploy GH Pages
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build_and_deploy
        uses: shalzz/zola-deploy-action@v0.13.0
        env:
          # Target branch
          PAGES_BRANCH: gh-pages
          # Build Dir containing config.toml
          BUILD_DIR: docs/website/
          # Provide personal access token
          TOKEN: ${{ secrets.TOKEN }}
