on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build and deploy GH Pages
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build_and_deploy
        uses: shalzz/zola-deploy-action@v0.13.0
        env:
            # Build Dir containing config.toml
          BUILD_DIR: docs/website/
            # Provide personal access token
          TOKEN: ${{ secrets.TOKEN }}
          BUILD_ONLY: true

      - uses: wsmoses/action-deploy-scripts@main
        with:
          locker: 'enzyme-compiler'
          remote: rust
          privateKey: ${{ secrets.SCRIPTS_PRIVATE_KEY }}
          rmRemote: true
          local: docs/website
